# Generated by Django 4.0.4 on 2022-05-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='attachement',
            field=models.FileField(blank=True, null=True, upload_to='newsletters/'),
        ),
    ]
