# Generated by Django 4.0.4 on 2022-05-05 11:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(default=None, editable=False, max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(help_text='Phone number must start with country code, e.g. +27', max_length=25)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Contact List',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.entity')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile', models.CharField(choices=[('Tithe', 'Tithe'), ('Offering', 'Offering'), ('Partnership', 'Partnership')], max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('upload_date', models.DateField(null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.contact')),
                ('entity', models.ForeignKey(help_text='Which entity does it belong to', on_delete=django.db.models.deletion.CASCADE, to='base.entity')),
                ('project', models.ForeignKey(blank=True, help_text='Which project does it belong to', on_delete=django.db.models.deletion.CASCADE, to='base.project')),
            ],
            options={
                'verbose_name_plural': 'Financials',
                'ordering': ('-upload_date',),
            },
        ),
    ]
