# Generated by Django 4.0.4 on 2022-05-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterField(
            model_name='financial',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
