# Generated by Django 4.0.4 on 2022-05-05 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_entity_options_alter_financial_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='financial',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='financial',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Which project does it belong to', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='upload_date',
            field=models.DateField(null=True),
        ),
    ]
