# Generated by Django 4.0.4 on 2022-05-06 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_financial_created_alter_financial_project_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financial',
            options={'ordering': ('-upload_date',), 'verbose_name_plural': 'Income'},
        ),
        migrations.AlterField(
            model_name='financial',
            name='upload_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField()),
                ('captured_date', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('entity', models.ForeignKey(help_text='Which entity does it belong to', on_delete=django.db.models.deletion.CASCADE, to='base.entity')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Which project does it belong to', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project')),
            ],
            options={
                'verbose_name_plural': 'Expenses',
                'ordering': ('-captured_date',),
            },
        ),
    ]
