# Generated by Django 4.0.4 on 2022-05-06 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_expenses_created_alter_expenses_captured_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='financial',
            name='entity',
            field=models.ForeignKey(help_text='Which entity does it belong to?', on_delete=django.db.models.deletion.CASCADE, to='base.entity'),
        ),
        migrations.AlterField(
            model_name='financial',
            name='profile',
            field=models.CharField(choices=[('Tithe', 'Tithe'), ('Offering', 'Offering'), ('Partnership', 'Partnership'), ('Pastors seed', 'Pastors seed')], help_text='What is the amount for?', max_length=200),
        ),
        migrations.AlterField(
            model_name='financial',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Which project does it belong to?', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.project'),
        ),
    ]
