# Generated by Django 4.0.4 on 2022-05-06 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_category_alter_financial_entity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='profile',
            field=models.ForeignKey(help_text='What is the amount for?', on_delete=django.db.models.deletion.CASCADE, to='base.category'),
        ),
    ]
