# Generated by Django 4.0.4 on 2022-05-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_contactcategory_contact_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactcategory',
            options={'verbose_name_plural': 'Contact Categories'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(default=None, editable=False, primary_key=True, serialize=False),
        ),
    ]
