# Generated by Django 4.0.4 on 2022-05-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_contactcategory_options_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.CharField(default=None, editable=False, max_length=15, primary_key=True, serialize=False),
        ),
    ]
