# Generated by Django 4.0.4 on 2022-05-25 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_contact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='code',
            field=models.CharField(default=None, editable=False, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.AutoField(default=None, editable=False, primary_key=True, serialize=False),
        ),
    ]
